### ISSUE TITLE
Did anyone able to stitch traffic coming from Open Telemetry and Axway

### ISSUE THREAD

**Issue by avinashpodisetti** [Axway-API-Management-Plus/dynatrace-apim-oneagent#24]
we implemented  Open Telemetry on cloudrun and ingested into Dynatrace.  Currently we are not able to stitch the traffic between these two. did anyone tried to stitch the traffic. Not a right spot to post this

**Comment by rathnapandi** [comment]
Hi @avinashpodisetti, 

Can you elaborate the requirements little more?

If you want Axway api gateway to send telemetry data in open telemetry format, we need to implement manual instrumentation using open telemetry SDK ( https://opentelemetry.io/docs/instrumentation/java/manual/).   

Thanks
Rathna

**Comment by juliusloman** [comment]
@rathnapandi I just ran into the same situation 2 weeks ago.

Since OpenTelemetry and W3C Trace Context are becoming industry standard for tracing, current solution is lacking the support for it.

Even Dynatrace uses W3C Trace Context for cross-environment integration. The customer situation is as follows:

1. Requests to API Gateway are received with existing W3C trace context (typically monitored in a different Ddynatrace environment or not monitored by Dynatrace). So they have the traceparent and tracestate headers.
2. OneAgent SDK does not have any methods of setting the trace context (trace id) when creating a tracer, so OneAgent creates a new Trace ID.
3. Additionally the outgoing request from the API gateway also does not have any W3C trace context information (actually possible [to get](https://github.com/Dynatrace/OneAgent-SDK-for-Java#trace-context)  although discouraged for this purpose. So again, traces can't be followed unless the services called by API gateway are monitored within the same Dynatrace environment.

So in the long term, it's inevitable to either have OpenTelemetry tracing support in AXWAY or rewrite this module with OpenTelemetry instead of OneAgent SDK to have proper support in more complex environments.

**Comment by rathnapandi** [comment]
Hi @juliusloman, 

Thanks for giving detailed information about the current fit falls and how to overcome, created a project [apim opentelemetry](https://github.com/Axway-API-Management-Plus/opentelemetry-apim-agent ) which implements OpenTelemetry SDK. 

Yet to add context support. 
@avinashpodisetti, can you start using the new project and add your changes?

Thanks
Rathna

**Comment by rathnapandi** [comment]
Hi @avinashpodisetti 
Added context propagation support to opentelmentery agent and closing this issue. 

If you see any issue, please open a separate defect. 

Thanks
Rathna

**Comment by avinashpodisetti** [comment]
@rathnapandi , sure.. will give it a try and let you know
